import Head from "next/head";
import styles from "../styles/Home.module.css";
import Cookies from "js-cookie";

export default function Home() {
    const cookie = Cookies.get("_some_cookie");
    console.log({ cookie });

    return (
        <div className={styles.container}>
            <Head>
                <title>Multi-Zone-App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>This is the multi zone app</h1>
                <p>This is the cookie: {cookie}</p>
            </main>
        </div>
    );
}
